name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2

      - name: Select Xcode
        run: sudo xcode-select -switch /Applications/Xcode.app

      - name: Build and test
        run: xcodebuild clean build test -project GithubActionsConfiguration.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator, id=dvtdevice-DVTiOSDeviceSimulatorPlaceholder-iphonesimulator=placeholder, name=Any iOS Simulator Device" ONLY_ACTIVE_ARCH=NO 
