name: iOS Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: iOS build setup
        run: >-
          xcodebuild clean test -project GithubActionsConfiguration.xcodeproj
          -scheme CI -destination 'platform=iOS Simulator,name=iPhone
          11,OS=15.0'
      - name: testing ... iPhone 11
        run: >-
          xcodebuild clean test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone
          11,OS=15.0'
      - name: testing ... iPhone 11 Pro Max
        run: >-
          xcodebuild test -workspace TestApp.xcodeproj/project.xcworkspace
          -scheme TestApp -destination 'platform=iOS Simulator,name=iPhone 11
          Pro Max,OS=15.0'
