name: iOS Test Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Build and Test default scheme using iPhone/iPad simulator
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Force Xcode 11
        run: sudo xcode-select -switch /Applications/Xcode.app
      - name: iOS build setup
        run: >-
          xcodebuild clean test -project GithubActionsConfiguration.xcodeproj
          -scheme CI -destination 'platform=iOS Simulator,name=iPhone 11,OS=latest'

