name: Pull Request

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: macos-latest

    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app

    steps:
      - uses: actions/checkout@v2
      - name: Build and test
        run: xcodebuild clean build test -project GithubActionsConfiguration.xcodeproj -scheme "CI" -sdk iphonesimulator -destination "platform=iOS Simulator,OS=16.4,name=iPhone 14" ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO